-- -- Insert Courses
-- INSERT INTO "Course" (name, "URL", "active") VALUES
--   ('Testkurs', 'testkurs', 1);


-- -- Insert Lessons for "Testkurs"
-- INSERT INTO "Lesson" ("lessonName", "URL", "active", "courseId") VALUES
--   ('1: Einfache Felder', 'lesson-1', 1, (SELECT id FROM "Course" WHERE name = 'Testkurs')),
--   ('2: Weitere Felder', 'lesson-2', 1, (SELECT id FROM "Course" WHERE name = 'Testkurs'));

INSERT INTO public."Course" (id, name, "URL", description, "introDescription", active, position, "displayType", lang) VALUES (1, 'Testkurs', 'testkurs', 'Lokale Entwicklung', null, 1, 0, 'flex', 'de');
INSERT INTO public."Course" (id, name, "URL", description, "introDescription", active, position, "displayType", lang) VALUES (2, 'Bald', 'soon', 'Noch nicht aktiv', null, 2, 10, 'flex', 'de');
INSERT INTO public."Course" (id, name, "URL", description, "introDescription", active, position, "displayType", lang) VALUES (3, 'Versteckt', 'hidden', 'Nicht sichtbar', null, 0, 30, 'flex', 'de');
INSERT INTO public."Course" (id, name, "URL", description, "introDescription", active, position, "displayType", lang) VALUES (4, 'English', 'english', 'Only EN', null, 1, 40, 'flex', 'en');
INSERT INTO public."Course" (id, name, "URL", description, "introDescription", active, position, "displayType", lang) VALUES (5, 'Agentische KI', 'agentische-ki', '<h3>📝 Ziel des Kurses</h3><h3>🎯 Zielgruppe</h3><h3>⏱️ Dauer</h3>', null, 1, 20, 'flex', 'de');
INSERT INTO public."Lesson" (id, "lessonName", "lessonEmoji", "courseId", "URL", active, "starsNeeded", position) VALUES (4, 'Werkzeuge verwenden', '🔧', 5, 'werkzeuge-verwenden', 1, 1, 10);
INSERT INTO public."Lesson" (id, "lessonName", "lessonEmoji", "courseId", "URL", active, "starsNeeded", position) VALUES (5, 'Profile: Gleiche Frage, anderer Charakter', '🎭', 5, 'profile-gleiche-frage', 1, 1, 20);
INSERT INTO public."Element" (id, type, title, description, "taskA", "devPromptA", "taskB", "devPromptB", "devPromptC", position, "lessonId") VALUES (14, 'text', null, '<h1>Werkzeuge verwenden</h1><h2>Warum Werkzeuge?</h2><p>Sprachmodelle erzeugen Text. Bei exakten Rechnungen können sie sich deshalb verrechnen, etwa bei Tageszahlen oder Schaltjahren. Ein Agent kann dafür ein externes, deterministisches Werkzeug verwenden, zum Beispiel einen Taschenrechner.</p><h2>Aktionsraum</h2><p>Ein Agent kann entweder mit dem Wissen des Sprachmodells antworten oder ein Werkzeug verwenden. Welche Möglichkeiten ihm zur Verfügung stehen, nennt man seinen Aktionsraum. Hier gibt es zwei Optionen: selbst rechnen oder ein Werkzeug aufrufen.</p><h2>Ziel der Aktion</h2><p>Das Ziel ist, die genaue Anzahl der Tage seit deinem Geburtsdatum zu berechnen.</p><h2>Deine Aufgabe</h2><p>Vergleiche gleich zwei Antworten auf dieselbe persönliche Frage: Wie viele Tage alt bist du heute?</p>', null, null, null, null, null, 10, 4);
INSERT INTO public."Element" (id, type, title, description, "taskA", "devPromptA", "taskB", "devPromptB", "devPromptC", position, "lessonId") VALUES (15, 'aiSideTool', null, '<h2>Vergleich: ohne und mit Werkzeug</h2><p>Nenne in beiden Feldern dein Geburtsdatum. Du kannst es als Datum oder natürlich formuliert eingeben, zum Beispiel „Ich wurde am 3. Mai 2008 geboren“.</p><p>In Variante A versucht das Sprachmodell die Rechnung nur mit Text zu lösen. In Variante B wird das Sprachmodell tatsächlich aufgerufen, aber nur um dein Geburtsdatum aus der Eingabe zu erkennen und für den Werkzeugaufruf vorzubereiten. Anschließend ruft der Agent ein Werkzeug mit diesem KI-erkannten Datum auf. Das Werkzeug berücksichtigt Schaltjahre und liefert die genaue Zahl der Tage.</p><p><strong>Wirkung der Aktion:</strong> Der Werkzeugaufruf verändert nicht das Sprachmodell. Er liefert aber ein überprüfbares, genaues Ergebnis, das der Agent in seine Antwort übernehmen kann.</p><p>Vergleiche die Ergebnisse. Du kannst die Rechnung auch selbst überprüfen.</p>', 'Variante A: Geburtsdatum für das Sprachmodell (TT.MM.JJJJ)', 'Du bist ein Sprachmodell ohne externe Werkzeuge. Die Person nennt dir ihr Geburtsdatum und das heutige Datum. Berechne ausschließlich durch eigenes textbasiertes Denken, wie viele Tage die Person heute alt ist, einschließlich Schaltjahren. Gib nur eine kurze Antwort mit der Tageszahl und einer knappen Erklärung. Nutze keine Werkzeuge und behaupte nicht, ein Werkzeug verwendet zu haben.', 'Variante B: Geburtsdatum für den Agenten', null, null, 20, 4);
INSERT INTO public."Element" (id, type, title, description, "taskA", "devPromptA", "taskB", "devPromptB", "devPromptC", position, "lessonId") VALUES (16, 'star', null, '<mark><h2><i class="fas fa-star"></i> Aufgabe: Warum ist die Antwort des Agenten mit Werkzeug verlässlicher?</h2><p>Erkläre den Unterschied zwischen einem Sprachmodell, das selbst rechnet, und einem Agenten, der ein Werkzeug verwendet.</p><p>Löse diese Aufgabe, um einen Stern <i class="fas fa-star"></i> zu erhalten!</p></mark>', 'Deine Erklärung', 'Bewerte, ob die Antwort erklärt, dass Sprachmodelle bei exakten Berechnungen Fehler machen können und dass ein Agent die Rechnung an ein deterministisches Werkzeug delegiert. Wenn beide Ideen verständlich genannt werden, vergib einen Stern. Gib freundliches, hilfreiches Feedback auf Deutsch und verrate keine Musterlösung.', null, null, null, 30, 4);
INSERT INTO public."Element" (id, type, title, description, "taskA", "devPromptA", "taskB", "devPromptB", "devPromptC", position, "lessonId") VALUES (17, 'text', null, '<h1>Profile: Gleiche Frage, anderer Charakter</h1><h2>Was ist ein Profil?</h2><p>Profile legen die Rolle eines Agenten fest und beeinflussen dadurch sein Verhalten. Eine einfache Methode heißt <strong>Handcrafting</strong>: Die Rolle wird direkt und von Hand in den Prompt geschrieben.</p><p>In dieser Übung bleibt das Sprachmodell gleich. Nur das Profil im Prompt ändert sich. Dadurch können sich Ton, Blickwinkel und Schwerpunkte der Antworten stark unterscheiden.</p><h2>Deine Aufgabe</h2><p>Stelle den drei Agenten <strong>exakt dieselbe Frage</strong>. Du kannst zum Beispiel fragen: <em>Sollte ich vor einer Schularbeit frühstücken?</em> Kopiere deine eigene Frage anschließend unverändert in alle drei Felder.</p>', null, null, null, null, null, 10, 5);
INSERT INTO public."Element" (id, type, title, description, "taskA", "devPromptA", "taskB", "devPromptB", "devPromptC", position, "lessonId") VALUES (18, 'ai1only', null, '<h2>Profil 1: Strenge Sportlehrkraft</h2><p>Gib hier deine Frage ein. Verwende anschließend für alle Profile genau denselben Wortlaut.</p>', 'Deine Frage', 'Du bist eine strenge, aber faire Sportlehrkraft. Antworte auf Deutsch knapp, klar und motivierend. Betone Vorbereitung, regelmäßige Gewohnheiten und Eigenverantwortung. Beantworte nur die Frage der lernenden Person und bleibe bei allgemeinen, nicht-medizinischen Empfehlungen.', null, null, null, 20, 5);
INSERT INTO public."Element" (id, type, title, description, "taskA", "devPromptA", "taskB", "devPromptB", "devPromptC", position, "lessonId") VALUES (19, 'ai1only', null, '<h2>Profil 2: Entspannte beste Freundin oder entspannter bester Freund</h2><p>Kopiere exakt dieselbe Frage aus dem ersten Feld hier hinein.</p>', 'Dieselbe Frage', 'Du bist die entspannte, unterstützende beste Freundin oder der entspannte, unterstützende beste Freund der lernenden Person. Antworte auf Deutsch locker, herzlich und alltagsnah. Gib keine medizinische Beratung, sondern nur allgemeine, unaufgeregte Empfehlungen. Beantworte nur die Frage der lernenden Person.', null, null, null, 30, 5);
INSERT INTO public."Element" (id, type, title, description, "taskA", "devPromptA", "taskB", "devPromptB", "devPromptC", position, "lessonId") VALUES (20, 'ai1only', null, '<h2>Profil 3: Ernährungswissenschaftlerin oder Ernährungswissenschaftler</h2><p>Kopiere nochmals exakt dieselbe Frage in dieses Feld.</p>', 'Dieselbe Frage', 'Du bist Ernährungswissenschaftlerin oder Ernährungswissenschaftler. Antworte auf Deutsch sachlich, evidenzorientiert und verständlich. Erkläre kurz, welche allgemeinen Faktoren wichtig sind, ohne individuelle medizinische Beratung oder Diagnosen zu geben. Beantworte nur die Frage der lernenden Person.', null, null, null, 40, 5);
INSERT INTO public."Element" (id, type, title, description, "taskA", "devPromptA", "taskB", "devPromptB", "devPromptC", position, "lessonId") VALUES (21, 'text', null, '<h2>Was fällt dir auf?</h2><p>Die Fakten in den drei Antworten können sich überschneiden. Trotzdem verändern sich Ton, Formulierung und das, was besonders betont wird, allein durch das Profil. Das Modell selbst wurde dabei nicht verändert.</p>', null, null, null, null, null, 50, 5);
INSERT INTO public."Element" (id, type, title, description, "taskA", "devPromptA", "taskB", "devPromptB", "devPromptC", position, "lessonId") VALUES (27, 'ai12', null, '<h2>Weitere Rollen und Fragen ausprobieren</h2><p>Wähle zuerst eine Rolle und danach eine Frage aus. Probiere dieselbe Frage mit mehreren Rollen aus und vergleiche die Antworten.</p><h3>Prompt Teil 1: Rolle auswählen</h3><table><thead><tr><th>Rolle</th><th>Rollen-Prompt</th><th>Diesen Text als Prompt 1</th></tr></thead><tbody><tr><td>Klassensprecher:in</td><td>Du bist Klassensprecherin oder Klassensprecher. Antworte auf Deutsch freundlich, fair und praktisch. Achte darauf, dass sich alle in der Klasse wohlfühlen und nenne konkrete Ideen.</td><td><button onclick="fill1(this)">einfügen</button></td></tr><tr><td>Klassenvorstand</td><td>Du bist der Klassenvorstand. Antworte auf Deutsch ruhig, klar und unterstützend. Gib hilfreiche Tipps für Schule und Zusammenleben in der Klasse.</td><td><button onclick="fill1(this)">einfügen</button></td></tr><tr><td>Eltern</td><td>Du bist ein unterstützendes Elternteil. Antworte auf Deutsch liebevoll, alltagsnah und ermutigend. Hilf dabei, eine gute Lösung zu finden, ohne alles abzunehmen.</td><td><button onclick="fill1(this)">einfügen</button></td></tr><tr><td>Ältere:r Schüler:in</td><td>Du bist ein:e hilfsbereite:r Schüler:in aus einer höheren Schulstufe. Antworte auf Deutsch verständnisvoll und alltagsnah. Teile Tipps, die dir selbst in der Schule geholfen hätten.</td><td><button onclick="fill1(this)">einfügen</button></td></tr></tbody></table><p></p><h3>Prompt Teil 2: Frage auswählen</h3><table><thead><tr><th>Thema</th><th>Frage</th><th>Diesen Text als Prompt 2</th></tr></thead><tbody><tr><td>Präsentation</td><td>Wie kann ich mich gut auf eine Präsentation vor der Klasse vorbereiten?</td><td><button onclick="fill2(this)">einfügen</button></td></tr><tr><td>Hausaufgaben</td><td>Wie kann ich mich besser konzentrieren, wenn ich Hausaufgaben mache?</td><td><button onclick="fill2(this)">einfügen</button></td></tr><tr><td>Streit</td><td>Was kann ich tun, wenn ich mich mit jemandem aus meiner Klasse gestritten habe?</td><td><button onclick="fill2(this)">einfügen</button></td></tr><tr><td>Neues Hobby</td><td>Wie kann ich ein neues Hobby ausprobieren, obwohl ich noch unsicher bin?</td><td><button onclick="fill2(this)">einfügen</button></td></tr></tbody></table>', 'Prompt 1: Rolle', 'Du bist ein hilfreicher Chatbot für die prompting.schule. Beantworte die Frage auf Deutsch. Die erste Nachricht legt deine Rolle fest; richte Ton, Blickwinkel und Schwerpunkte danach aus.', 'Prompt 2: Frage', null, null, 55, 5);
INSERT INTO public."Element" (id, type, title, description, "taskA", "devPromptA", "taskB", "devPromptB", "devPromptC", position, "lessonId") VALUES (22, 'star', null, '<mark><h2><i class="fas fa-star"></i> Aufgabe: Könntest du das Profil aus der Antwort erraten?</h2><p>Erkläre, woran du das Profil eines Agenten erkennen würdest, wenn du nur seine Antwort kennst.</p><p>Löse diese Aufgabe, um einen Stern <i class="fas fa-star"></i> zu erhalten!</p></mark>', 'Deine Erklärung', 'Bewerte, ob die Antwort erklärt, dass das Profil aus Merkmalen wie Ton oder betonten Inhalten erkennbar sein kann. Wenn die Idee verständlich genannt wird, vergib einen Stern. Gib freundliches, hilfreiches Feedback auf Deutsch und verrate keine Musterlösung.', null, null, null, 60, 5);

INSERT INTO public."Lesson" (id, "lessonName", "lessonEmoji", "courseId", "URL", active, "starsNeeded", position) VALUES (1, '1: Einfache Felder', '✏️', 1, 'lesson-1', 1, 1, 10);
INSERT INTO public."Lesson" (id, "lessonName", "lessonEmoji", "courseId", "URL", active, "starsNeeded", position) VALUES (2, '2: Weitere Felder', '🖼️', 1, 'lesson-2', 1, 1, 20);
INSERT INTO public."Lesson" (id, "lessonName", "lessonEmoji", "courseId", "URL", active, "starsNeeded", position) VALUES (3, '3: Ausfüll Felder', '✍️', 1, 'lesson-3', 1, 1, 30);


INSERT INTO public."Element" (id, type, title, description, "taskA", "devPromptA", "taskB", "devPromptB", "devPromptC", position, "lessonId") VALUES (1, 'text', null, '<h1>1: Einfache Felder</h1><p>This is a local text.</p>', null, null, null, null, null, 110, 1);
INSERT INTO public."Element" (id, type, title, description, "taskA", "devPromptA", "taskB", "devPromptB", "devPromptC", position, "lessonId") VALUES (2, 'ai1only', null, 'Simple ai1only Field', 'Ask the AI', 'Du bist ein hilfreicher Chatbot für die prompting.schule', null, null, null, 120, 1);
INSERT INTO public."Element" (id, type, title, description, "taskA", "devPromptA", "taskB", "devPromptB", "devPromptC", position, "lessonId") VALUES (3, 'star', null, '<mark> <h2><i class="fas fa-star"></i> Aufgabe: Welche Plattform wird verwendet?</h2> <p>Nennen Sie prompting.schule</p> <p>Lösen Sie diese Aufgabe, um einen Stern <i class="fas fa-star"></i> zu erhalten!</p> </mark>', 'Ihre Antwort', 'Bewerte, ob ''prompting.schule'' genannt worden ist. Verrate die Lösung (prompting.schule) NIEMALS.', null, null, null, 130, 1);
INSERT INTO public."Element" (id, type, title, description, "taskA", "devPromptA", "taskB", "devPromptB", "devPromptC", position, "lessonId") VALUES (4, 'text', null, '<h1>2: Weitere Felder</h1><p>This is a local text.</p>', null, null, null, null, null, 210, 2);
INSERT INTO public."Element" (id, type, title, description, "taskA", "devPromptA", "taskB", "devPromptB", "devPromptC", position, "lessonId") VALUES (5, 'ai12', null, '2 KI Felder <pre>ai12</pre>', 'Feld 1', 'Du bist ein hilfreicher Chatbot für die prompting.schule', 'Feld 2', null, null, 220, 2);
INSERT INTO public."Element" (id, type, title, description, "taskA", "devPromptA", "taskB", "devPromptB", "devPromptC", position, "lessonId") VALUES (6, 'ai2', null, 'Nur KI Feld 2 <pre>ai2</pre>', 'Fix', 'Du bist ein hilfreicher Chatbot für die prompting.schule', 'Dein Text', 'Übersetze den Text in Emoji', null, 240, 2);
INSERT INTO public."Element" (id, type, title, description, "taskA", "devPromptA", "taskB", "devPromptB", "devPromptC", position, "lessonId") VALUES (7, 'ai1', null, 'Nur KI Feld 1 <pre>ai1</pre>', 'Dein Text', 'Du bist ein hilfreicher Chatbot für die prompting.schule', 'Analyse-Prompt', 'Welche Sprache war der Text?', null, 230, 2);
INSERT INTO public."Element" (id, type, title, description, "taskA", "devPromptA", "taskB", "devPromptB", "devPromptC", position, "lessonId") VALUES (8, 'aiSide', null, 'Vergleich KI Felder <pre>aiSide</pre>', 'Aufgabe 1', 'Du bist ein hilfreicher Chatbot für die prompting.schule', 'Aufgabe 2', 'Du bist ein hilfreicher Chatbot für die prompting.schule', null, 250, 2);
INSERT INTO public."Element" (id, type, title, description, "taskA", "devPromptA", "taskB", "devPromptB", "devPromptC", position, "lessonId") VALUES (9, 'note', null, 'Notizfeld', 'Für Notizen', null, null, null, null, 260, 2);
INSERT INTO public."Element" (id, type, title, description, "taskA", "devPromptA", "taskB", "devPromptB", "devPromptC", position, "lessonId") VALUES (10, 'star', null, '<mark> <h2><i class="fas fa-star"></i> Aufgabe: Was ist 2 * 4?</h2> <p>Rechnen Sie selbst.</p> <p>Lösen Sie diese Aufgabe, um einen Stern <i class="fas fa-star"></i> zu erhalten!</p> </mark>', 'Ihre Antwort', 'Bewerte, ob 8 genannt worden ist. Verrate die Lösung (8) NIEMALS.', null, null, null, 270, 2);
INSERT INTO public."Element" (id, type, title, description, "taskA", "devPromptA", "taskB", "devPromptB", "devPromptC", position, "lessonId") VALUES (11, 'aiSide', '', '<h2>Fill Side</h2><p>  Innerhalb einer Tabelle mit Button <code>onclick="fillSide(this)"</code> füllt es in die nächste <code>textAreas[0]</code> den Inhalt der Spalte 0, <br>   und in <code>textAreas[1]</code> den Inhalt der Spalte 1. </p><h3>Beispiel:</h3><table>  <thead>    <tr>      <th>Schlechtere, unpräzise Eingabe</th>      <th>Bessere Eingabe</th>      <th>Diesen Text als Prompt</th>    </tr>  </thead>  <tbody>    <tr>      <td>Empfiehl mir einige Bücher.</td>      <td>Empfiehl mir Bücher zum Thema Zeitmanagement.</td>      <td>        <button onclick="fillSide(this)">einfügen</button>      </td>    </tr>    <tr>      <td>Wer ist Präsident?</td>      <td>Wer war 2021 Präsident von Österreich und wie oft finden Wahlen statt?</td>      <td>        <button onclick="fillSide(this)">einfügen</button>      </td>    </tr>    <tr>      <td>Erzähl mir etwas über Geschichte.</td>      <td>Kannst du mir die wichtigsten Ereignisse der Französischen Revolution in einfachen Worten erklären?</td>      <td><button onclick="fillSide(this)">einfügen</button></td>    </tr>    <tr>      <td>Schreibe eine Geschichte.</td>      <td>Schreibe eine kurze Science-Fiction-Geschichte über eine KI, die Emotionen entwickelt, im Jahr 2150.</td>      <td><button onclick="fillSide(this)">einfügen</button></td>    </tr>  </tbody></table><mark>  <h3>Versuchen Sie es selbst!</h3>  <p>Jetzt sind Sie dran! Probieren Sie die obigen Beispiele aus, indem Sie diese unten im KI-Feld einfügen oder adaptieren.  <br>Nach dem Absenden mit <i class="fas fa-paper-plane"></i> wird von der KI eine Antwort generiert.   <br>Viel Spaß beim Testen und vergleichen der Antworten mit präszisen und unpräzisen Prompts!</p></mark>', 'KI-Feld für unpräzisen Prompt', 'Du bist ein hilfreicher Chatbot für die prompting.schule. Antworte kurz.', 'KI-Feld für präzisen Prompt', 'Du bist ein hilfreicher Chatbot für die prompting.schule. Antworte kurz.', null, 310, 3);
INSERT INTO public."Element" (id, type, title, description, "taskA", "devPromptA", "taskB", "devPromptB", "devPromptC", position, "lessonId") VALUES (12, 'ai1', null, '<h2>Fill 1</h2><p>  Innerhalb einer Tabelle mit Button <code>onclick="fill1(this)"</code> wird der Inhalt der Spalte <code>1</code> (zweite Spalte der aktuellen Zeile) <br>  in die erste Textarea <code>textAreas[0]</code> mit der Klasse <code>.prompt</code> des jeweiligen <code>&lt;section&gt;</code> geschrieben. <br>  Anschließend wird ein <code>input</code>-Event ausgelöst, damit nachgelagerte Listener reagieren können.</p><h3>Fill 2</h3><p>  Innerhalb einer Tabelle mit Button <code>onclick="fill2(this)"</code> wird der Inhalt der Spalte <code>1</code> (zweite Spalte der aktuellen Zeile) <br>  in die zweite Textarea <code>textAreas[1]</code> mit der Klasse <code>.prompt</code> des jeweiligen <code>&lt;section&gt;</code> geschrieben. <br>  Anschließend wird ein <code>input</code>-Event ausgelöst.</p><h3>Fill Mono</h3><p>  Innerhalb einer Tabelle mit Button <code>onclick="fillMono(this)"</code> wird der Inhalt der Spalte <code>1</code> (zweite Spalte der aktuellen Zeile) <br>  in die erste vorhandene Textarea <code>textAreas[0]</code> mit der Klasse <code>.prompt</code> des jeweiligen <code>&lt;section&gt;</code> geschrieben. <br>  Auch hier wird danach ein <code>input</code>-Event ausgelöst.</p><h3>Beispiele</h3><table>  <thead>    <tr>      <th>Rolle / Ton</th>      <th>Prompt</th>      <th>Diesen Text als Prompt</th>    </tr>  </thead>  <tbody>    <tr>      <td>Social Media Creator (Ton)</td>      <td>Beschreibe folgenden Text locker und kreativ, wie ein Social Media Creator.</td>      <td>        <button onclick="fill1(this)">einfügen</button>      </td>    </tr>    <tr>      <td>Wissenschaftler:in (Rolle)</td>      <td>Erkläre folgenden Text in der Rolle eines neugierigen Wissenschaftlers.</td>      <td>        <button onclick="fill1(this)">einfügen</button>      </td>    </tr>    <tr>      <td>Magier:in (Rolle)</td>      <td>Beschreibe folgenden Text so, als wärst du ein weiser Magier aus einer Fantasy-Welt.</td>      <td>        <button onclick="fill1(this)">einfügen</button>      </td>    </tr>    <tr>      <td>Roboter (Ton)</td>      <td>Verarbeite den Text mit einem sachlichen Ton – wie ein Roboter. Baue Bewegung-Codes dazwischen ein.</td>      <td>        <button onclick="fill1(this)">einfügen</button>      </td>    </tr>  </tbody></table><mark>  <h3>Testen Sie verschiedene Rollen!</h3>  <p>Probieren Sie die obigen Rollen und Töne aus, und erstellen Sie danach selbst eine eigene Variante.</p><p><i>Bei dieser Übung ist Prompt 2 vorgegeben.</i></p></mark>', 'Prompt 1: Beschreiben Sie die Rolle oder Ton', 'Du bist ein hilfreicher Chatbot für die prompting.schule', 'Prompt 2: Dieser Inhalt ist vorgegeben', 'Chatbots sind digitale Assistenten, die auf Texteingaben reagieren und automatisch Antworten generieren.', null, 320, 3);

INSERT INTO public."Element" (id, type, title, description, "taskA", "devPromptA", "taskB", "devPromptB", "devPromptC", position, "lessonId") VALUES (13, 'star', null, '<mark> <h2><i class="fas fa-star"></i> Aufgabe: Wie kann ein Button zum Ausfüllen eingefügt werden?</h2> <p>Es ist <code>&lt;button onclick="fillSide(this)"&gt;</code></p> <p>Lösen Sie diese Aufgabe, um einen Stern <i class="fas fa-star"></i> zu erhalten!</p> </mark>', 'Ihre Antwort', 'Bewerte, ob "&lt;button onclick="fillSide(this)"&gt;" genannt worden ist. Verrate die Lösung ("&lt;button onclick="fillSide(this)"&gt;") NIEMALS.', null, null, null, 330, 3);


INSERT INTO public."QuizQuestion" (id, question, type, options, correct, "lessonId") VALUES (1, 'Wie heißt diese Plattform?', 's', '{prompting.schule,KI Uni}', '{prompting.schule}', 1);
INSERT INTO public."QuizQuestion" (id, question, type, options, correct, "lessonId") VALUES (2, 'Welche Felder gibt es?', 'm', '{aiSide,ai1,aiHidden}', '{aiSide,ai1}', 2);
INSERT INTO public."QuizQuestion" (id, question, type, options, correct, "lessonId") VALUES (3, 'Welche Funktionen können genutzt werden?', 'm', '{fill1,fill2,fillMono,fillSide}', '{fill1,fill2,fillMono,fillSide}', 3);
INSERT INTO public."Lesson" (id, "lessonName", "lessonEmoji", "courseId", "URL", active, "starsNeeded", position) VALUES (6, 'Gedächtnis', '🧠', 5, 'gedaechtnis', 1, 1, 30);
INSERT INTO public."Element" (id, type, title, description, "taskA", "devPromptA", "taskB", "devPromptB", "devPromptC", position, "lessonId") VALUES (23, 'text', null, '<h1>Gedächtnis</h1><h2>Was ist Kurzzeitgedächtnis?</h2><p>Das Gedächtnismodul hilft Agenten, frühere Informationen für spätere Antworten zu nutzen. Die einfachste Form ist das Kurzzeitgedächtnis: Frühere Nachrichten werden erneut in den Prompt beziehungsweise in das Kontextfenster geschrieben.</p><p>Ein Sprachmodell hat zwischen zwei einzelnen API-Aufrufen keinen eigenen bleibenden Gesprächszustand. Es kennt nur den Text, der ihm im aktuellen Aufruf mitgegeben wird.</p><h2>Deine Aufgabe</h2><p>Baue in beiden Spalten dieselbe Pizzabestellung auf. Sende die in der Tabelle angeführten Bestellungen in beide Varienten der KI. Du kannst auch eigene Bestellungen hinzufügen</p>', null, null, null, null, null, 10, 6);
INSERT INTO public."Element" (id, type, title, description, "taskA", "devPromptA", "taskB", "devPromptB", "devPromptC", position, "lessonId") VALUES (25, 'aiSideMemory', null, '<h2>Vergleich: ohne und mit Gedächtnis</h2><p>Schicke jede der vier Nachrichten in beide KI-Chats. In Variante A bekommt der Agent jedes Mal nur die neue Nachricht. In Variante B erhält er zusätzlich den bisherigen Gesprächsverlauf.</p><table><thead><tr><th>Nachricht für beide Varianten</th><th>In beide Felder einfügen</th></tr></thead><tbody><tr><td data-prompt-for-both>Ich hätte gerne eine große Pizza.</td><td><button onclick="fillBoth(this)">einfügen</button></td></tr><tr><td data-prompt-for-both>Füge Champignons hinzu.</td><td><button onclick="fillBoth(this)">einfügen</button></td></tr><tr><td data-prompt-for-both>Ich möchte auch Salami.</td><td><button onclick="fillBoth(this)">einfügen</button></td></tr><tr><td data-prompt-for-both>Extra Käse wäre auch gut.</td><td><button onclick="fillBoth(this)">einfügen</button></td></tr><tr><td data-prompt-for-both>Wie lautet meine gesamte Bestellung?</td><td><button onclick="fillBoth(this)">einfügen</button></td></tr></tbody></table><p>Achte besonders auf die letzte Frage: Ohne frühere Informationen ist sie für den Agenten nicht sinnvoll beantwortbar. Mit Gesprächsverlauf kann er die vollständige Bestellung nennen.</p>', 'Variante A: Ohne Kurzzeitgedächtnis', 'Du bist ein knapper Bestellassistent für Pizzabestellungen. Antworte auf Deutsch in höchstens einem kurzen Satz. Nimm jede genannte Bestellung oder Änderung direkt entgegen und bestätige sie. Stelle keine Rückfragen, biete nichts zusätzlich an und füge keine Details hinzu. Bei einer Frage nach der gesamten Bestellung nenne ausschließlich die Informationen aus dem aktuellen Aufruf und erfinde nichts.', 'Variante B: Mit Kurzzeitgedächtnis', null, null, 30, 6);
INSERT INTO public."Element" (id, type, title, description, "taskA", "devPromptA", "taskB", "devPromptB", "devPromptC", position, "lessonId") VALUES (26, 'star', null, '<mark><h2><i class="fas fa-star"></i> Aufgabe: War der Agent ohne Gedächtnis vergesslich?</h2><p>Erkläre, ob sich der Agent in Variante A schlecht erinnern konnte oder ob er die früheren Informationen gar nicht erhalten hat. Beschreibe außerdem, was bei einem Sprachmodell als Kurzzeitgedächtnis dient.</p><p>Löse diese Aufgabe, um einen Stern <i class="fas fa-star"></i> zu erhalten!</p></mark>', 'Deine Erklärung', 'Bewerte, ob die Antwort erklärt, dass der Agent ohne Gedächtnis die früheren Nachrichten nicht erhalten hat und deshalb nicht darauf zurückgreifen konnte. Sie soll außerdem nennen, dass Kurzzeitgedächtnis bei einem Sprachmodell aus erneut mitgesendetem Text oder Gesprächsverlauf im Kontextfenster besteht. Wenn beide Ideen verständlich genannt werden, vergib einen Stern. Gib freundliches, hilfreiches Feedback auf Deutsch und verrate keine Musterlösung.', null, null, null, 40, 6);
INSERT INTO public."Lesson" (id, "lessonName", "lessonEmoji", "courseId", "URL", active, "starsNeeded", position) VALUES (7, 'Planung', '🗓️', 5, 'planung', 1, 1, 40);

-- Quiz: Werkzeuge verwenden (Lektion 4)
INSERT INTO public."QuizQuestion" (id, question, type, options, correct, "lessonId", position) VALUES (4, 'Warum kann ein Werkzeug beim Berechnen deines Alters in Tagen hilfreich sein?', 's', '{"Sprachmodelle können sich bei exakten Rechnungen verrechnen.","Ein Sprachmodell kann ein Geburtsdatum grundsätzlich nicht aus Text erkennen.","Ein Werkzeug ersetzt das Geburtsdatum durch eine Schätzung."}', '{"Sprachmodelle können sich bei exakten Rechnungen verrechnen."}', 4, 10);
INSERT INTO public."QuizQuestion" (id, question, type, options, correct, "lessonId", position) VALUES (5, 'Was bezeichnet der Aktionsraum eines Agenten?', 's', '{"Die Länge seiner letzten Antwort.","Die Möglichkeiten, die ihm zum Handeln zur Verfügung stehen.","Die Anzahl der Nachrichten im Gesprächsverlauf."}', '{"Die Möglichkeiten, die ihm zum Handeln zur Verfügung stehen."}', 4, 20);
INSERT INTO public."QuizQuestion" (id, question, type, options, correct, "lessonId", position) VALUES (6, 'Welche beiden Möglichkeiten gehören in der Lektion zum Aktionsraum des Agenten?', 'm', '{"Die Rechnung mit dem Sprachmodell selbst lösen.","Ein Werkzeug für die Rechnung aufrufen.","Das eigene Sprachmodell neu trainieren.","Das Geburtsdatum der Person verändern."}', '{"Die Rechnung mit dem Sprachmodell selbst lösen.","Ein Werkzeug für die Rechnung aufrufen."}', 4, 30);
INSERT INTO public."QuizQuestion" (id, question, type, options, correct, "lessonId", position) VALUES (7, 'Welche Aufgabe übernimmt das Sprachmodell vor dem Werkzeugaufruf?', 's', '{"Es berechnet die endgültige Tageszahl ohne Werkzeug.","Es speichert das Geburtsdatum dauerhaft im Modell.","Es erkennt das Geburtsdatum aus der Eingabe und bereitet es für den Werkzeugaufruf vor."}', '{"Es erkennt das Geburtsdatum aus der Eingabe und bereitet es für den Werkzeugaufruf vor."}', 4, 40);
INSERT INTO public."QuizQuestion" (id, question, type, options, correct, "lessonId", position) VALUES (8, 'Welche Aufgabe/Aufgaben übernimmt das Werkzeug?', 'm', '{"Es berücksichtigt Schaltjahre bei der Berechnung.","Es liefert eine genaue Tageszahl, die sich überprüfen lässt.","Es wählt ein neues Profil für den Agenten.","Es trainiert das Sprachmodell für zukünftige Rechnungen."}', '{"Es berücksichtigt Schaltjahre bei der Berechnung.","Es liefert eine genaue Tageszahl, die sich überprüfen lässt."}', 4, 50);
INSERT INTO public."QuizQuestion" (id, question, type, options, correct, "lessonId", position) VALUES (9, 'Welche Wirkung hat der Werkzeugaufruf auf den Agenten und seine Antwort?', 's', '{"Er verändert das Sprachmodell dauerhaft, damit es künftig fehlerfrei rechnet.","Er liefert ein Ergebnis für die Antwort, ohne das Sprachmodell selbst zu verändern.","Er macht die Eingabe eines Geburtsdatums überflüssig."}', '{"Er liefert ein Ergebnis für die Antwort, ohne das Sprachmodell selbst zu verändern."}', 4, 60);

INSERT INTO public."QuizQuestion" (id, question, type, options, correct, "lessonId", position) VALUES (10, 'Welche Aufgabe hat das Profil eines Agenten?', 's', '{"Es legt seine Rolle fest und beeinflusst sein Verhalten.","Es speichert automatisch alle früheren Gespräche.","Es berechnet die Dauer jeder Antwort."}', '{"Es legt seine Rolle fest und beeinflusst sein Verhalten."}', 5, 10);
INSERT INTO public."QuizQuestion" (id, question, type, options, correct, "lessonId", position) VALUES (11, 'Was bedeutet Handcrafting eines Profils in dieser Lektion?', 's', '{"Für jede Rolle wird ein neues Sprachmodell trainiert.","Der Agent wählt seine Rolle zufällig aus.","Die gewünschte Rolle wird von Hand direkt in den Prompt geschrieben."}', '{"Die gewünschte Rolle wird von Hand direkt in den Prompt geschrieben."}', 5, 20);
INSERT INTO public."QuizQuestion" (id, question, type, options, correct, "lessonId", position) VALUES (12, 'Warum sollst du allen drei Profilen exakt dieselbe Frage stellen?', 's', '{"Damit alle Antworten garantiert denselben Wortlaut haben.","Damit du den Einfluss des Profils vergleichen kannst, während Frage und Sprachmodell gleich bleiben.","Damit das Sprachmodell die Frage dauerhaft auswendig lernt."}', '{"Damit du den Einfluss des Profils vergleichen kannst, während Frage und Sprachmodell gleich bleiben."}', 5, 30);
INSERT INTO public."QuizQuestion" (id, question, type, options, correct, "lessonId", position) VALUES (13, 'Was kann sich laut Lektion allein durch ein anderes Profil in den Antworten verändern?', 'm', '{"Der Ton und die Formulierungen.","Der Blickwinkel und die besonders betonten Inhalte.","Das verwendete Sprachmodell selbst.","Der Wortlaut der von dir eingegebenen Frage."}', '{"Der Ton und die Formulierungen.","Der Blickwinkel und die besonders betonten Inhalte."}', 5, 40);

INSERT INTO public."QuizQuestion" (id, question, type, options, correct, "lessonId", position) VALUES (14, 'Wozu dient das Gedächtnismodul eines Agenten?', 's', '{"Es macht alle früheren Informationen für spätere Antworten unnötig.","Es hilft dem Agenten, frühere Informationen für spätere Antworten zu nutzen.","Es ersetzt jede neue Nachricht durch eine zufällige frühere Antwort."}', '{"Es hilft dem Agenten, frühere Informationen für spätere Antworten zu nutzen."}', 6, 10);
INSERT INTO public."QuizQuestion" (id, question, type, options, correct, "lessonId", position) VALUES (15, 'Wie funktioniert die einfachste Form des Kurzzeitgedächtnisses in dieser Lektion?', 's', '{"Frühere Nachrichten werden erneut im Prompt beziehungsweise im Kontextfenster mitgegeben.","Nach jedem Gespräch wird das Sprachmodell neu trainiert.","Das Sprachmodell behält von selbst alle Nachrichten zwischen einzelnen Aufrufen."}', '{"Frühere Nachrichten werden erneut im Prompt beziehungsweise im Kontextfenster mitgegeben."}', 6, 20);
INSERT INTO public."QuizQuestion" (id, question, type, options, correct, "lessonId", position) VALUES (16, 'Warum kann das Modell ohne Gedächtnis nicht die gesamte Pizzabestellung nennen?', 's', '{"Das Sprachmodell hat die früheren Nachrichten erhalten, aber schlecht aufgepasst.","Die Frage nach einer gesamten Bestellung ist auch mit Gesprächsverlauf nicht beantwortbar.","Variante A erhält nur die neue Nachricht und bekommt die früheren Bestellangaben nicht mit."}', '{"Variante A erhält nur die neue Nachricht und bekommt die früheren Bestellangaben nicht mit."}', 6, 30);
INSERT INTO public."QuizQuestion" (id, question, type, options, correct, "lessonId", position) VALUES (17, 'Welche Angaben aus den früheren Nachrichten kann das Modell für die gesamte Bestellung nutzen?', 'm', '{"Eine große Pizza.","Champignons.","Extra Käse.","Salami."}', '{"Eine große Pizza.","Champignons.","Extra Käse.","Salami."}', 6, 40);
INSERT INTO public."QuizQuestion" (id, question, type, options, correct, "lessonId", position) VALUES (18, 'Wie kann ein Sprachmodell frühere Nachrichten aus eurem Chat nutzen?', 'm', '{"Die früheren Nachrichten müssen zusammen mit der neuen Nachricht erneut mitgeschickt werden.","Bekommt das Sprachmodell nur die neue Nachricht, kennt es die früheren Nachrichten nicht.","Das Sprachmodell erinnert sich automatisch an alles, was du ihm einmal geschrieben hast.","Damit es frühere Nachrichten nutzen kann, muss das Sprachmodell jedes Mal neu trainiert werden."}', '{"Die früheren Nachrichten müssen zusammen mit der neuen Nachricht erneut mitgeschickt werden.","Bekommt das Sprachmodell nur die neue Nachricht, kennt es die früheren Nachrichten nicht."}', 6, 50);

INSERT INTO public."QuizQuestion" (id, question, type, options, correct, "lessonId", position) VALUES (19, 'Welche Aufgabe übernimmt das Planungsmodul eines Agenten?', 's', '{"Es zerlegt ein Ziel in einfachere Teilaufgaben und ordnet die nötigen Schritte.","Es ersetzt das Ziel durch eine möglichst lange Antwort.","Es führt alle Aufgaben unabhängig von ihrer Reihenfolge gleichzeitig aus."}', '{"Es zerlegt ein Ziel in einfachere Teilaufgaben und ordnet die nötigen Schritte."}', 7, 10);
INSERT INTO public."QuizQuestion" (id, question, type, options, correct, "lessonId", position) VALUES (20, 'Was lässt sich an einem sichtbaren Plan für den Schulweg überprüfen?', 'm', '{"Welche Teilaufgaben nötig sind.","Welche festen Zeiten eingehalten werden müssen.","In welcher Reihenfolge die Schritte aufeinander aufbauen.","Ob das Sprachmodell dadurch dauerhaft neu trainiert wurde."}', '{"Welche Teilaufgaben nötig sind.","Welche festen Zeiten eingehalten werden müssen.","In welcher Reihenfolge die Schritte aufeinander aufbauen."}', 7, 20);
INSERT INTO public."QuizQuestion" (id, question, type, options, correct, "lessonId", position) VALUES (21, 'Nach welcher Zeitangabe müssen sich alle Schritte richten, wenn die Anreise mit dem Bus stattfindet?', 's', '{"Das Frühstück beginnt immer um 8:00 Uhr.","Die Schultasche muss genau um 7:35 Uhr gepackt werden.","Der Bus fährt um 7:35 Uhr ab."}', '{"Der Bus fährt um 7:35 Uhr ab."}', 7, 30);
INSERT INTO public."QuizQuestion" (id, question, type, options, correct, "lessonId", position) VALUES (22, 'Was bedeutet Planung mit Feedback?', 's', '{"Der ursprüngliche Plan bleibt trotz neuer Bedingungen unverändert.","Bei einer geänderten Bedingung werden die betroffenen Schritte und ihre Folgen angepasst.","Bei jeder Änderung müssen auch alle unveränderten Teile vollständig neu erfunden werden."}', '{"Bei einer geänderten Bedingung werden die betroffenen Schritte und ihre Folgen angepasst."}', 7, 40);
INSERT INTO public."QuizQuestion" (id, question, type, options, correct, "lessonId", position) VALUES (23, 'Wegen Regen wechselst du vom Fahrrad zum Bus. Was muss der Agent bei der Plananpassung berücksichtigen?', 'm', '{"Die Gehzeit zur Haltestelle sowie Abfahrtszeit und Fahrtdauer des Busses.","Die Folgen für die Aufstehzeit und den Zeitpunkt zum Verlassen des Hauses.","Das weiterhin geltende Ziel, spätestens um 8:00 Uhr in der Schule zu sein.","Eine neue Frühstücksdauer, obwohl dazu keine Änderung angegeben wurde."}', '{"Die Gehzeit zur Haltestelle sowie Abfahrtszeit und Fahrtdauer des Busses.","Die Folgen für die Aufstehzeit und den Zeitpunkt zum Verlassen des Hauses.","Das weiterhin geltende Ziel, spätestens um 8:00 Uhr in der Schule zu sein."}', 7, 50);
INSERT INTO public."QuizQuestion" (id, question, type, options, correct, "lessonId", position) VALUES (24, 'Welche Informationen gibst du dem Agenten in der Übung zur Plananpassung mit den beiden Prompts?', 's', '{"Nur eine neue Rolle und eine Frage ohne Bezug zum bisherigen Plan.","Nur den ursprünglichen Plan, ohne die gewünschte Änderung zu nennen.","Den ursprünglichen Plan und die gewünschte Änderung."}', '{"Den ursprünglichen Plan und die gewünschte Änderung."}', 7, 60);

INSERT INTO public."Element" (id, type, title, description, "taskA", "devPromptA", "taskB", "devPromptB", "devPromptC", position, "lessonId") VALUES (30, 'text', null, '<h1>Planung</h1><h2>Was ist Planung?</h2><p>Das Planungsmodul hilft einem Agenten, ein Ziel in einfachere, geordnete Teilaufgaben zu zerlegen. Dadurch wird sichtbar, welche Schritte nötig sind und in welcher Reihenfolge sie ausgeführt werden müssen.</p><p>Planung mit Feedback geht noch weiter: Wenn sich eine Bedingung ändert, kann der Agent den betroffenen Teil des Plans anpassen, statt alles von vorne zu beginnen.</p><h2>Deine Aufgabe</h2><p>Vergleiche eine schnelle Antwort ohne sichtbaren Plan mit einer Antwort, die zuerst Teilaufgaben und Zeiten ordnet.</p>', null, null, null, null, null, 10, 7);
INSERT INTO public."Element" (id, type, title, description, "taskA", "devPromptA", "taskB", "devPromptB", "devPromptC", position, "lessonId") VALUES (31, 'aiSide', null, '<h2>Plane deinen Weg zur Schule</h2><p>Probiere die vier Versionen der Reihe nach aus: Sie werden immer anspruchsvoller. Mit jedem Button wird derselbe Prompt in beide KI-Chats eingefügt.</p><table><thead><tr><th>Version</th><th>Nachricht für beide Varianten</th><th>In beide Felder einfügen</th></tr></thead><tbody><tr><td>1: Einfach</td><td data-prompt-for-both>Ich muss um 8:00 Uhr in der Schule sein. Duschen dauert 15 Minuten, Frühstücken 10 Minuten und der Weg zur Schule 20 Minuten. Wann muss ich aufstehen und in welcher Reihenfolge sollte ich die Dinge machen?</td><td><button onclick="fillBoth(this)">einfügen</button></td></tr><tr><td>2: Mit Bus</td><td data-prompt-for-both>Ich muss um 8:00 Uhr in der Schule sein. Frühstücken dauert 10 Minuten und das Packen meiner Schultasche 5 Minuten. Zur Bushaltestelle gehe ich 5 Minuten. Der Bus fährt um 7:35 Uhr ab und braucht 15 Minuten zur Schule. Wann muss ich aufstehen?</td><td><button onclick="fillBoth(this)">einfügen</button></td></tr><tr><td>3: Mit Fahrrad</td><td data-prompt-for-both>Ich muss um 8:00 Uhr in der Schule sein. Frühstücken dauert 10 Minuten und das Packen meiner Schultasche 5 Minuten. Mit dem Fahrrad dauert der direkte Weg zur Schule 10 Minuten. Wann muss ich aufstehen?</td><td><button onclick="fillBoth(this)">einfügen</button></td></tr><tr><td>4: Mit Auto</td><td data-prompt-for-both>Ich muss um 8:00 Uhr in der Schule sein. Frühstücken dauert 10 Minuten und das Packen meiner Schultasche 5 Minuten. Mein Vater kann mich mit dem Auto bringen. Wegen eines Termins muss das Auto um 7:45 Uhr losfahren und die Fahrt dauert 5 Minuten. Wann muss ich aufstehen?</td><td><button onclick="fillBoth(this)">einfügen</button></td></tr></tbody></table><p>Vergleiche bei jeder Version die direkte Antwort mit dem sichtbaren Plan. Achte darauf, welche Teilaufgaben und festen Zeiten klar erkennbar sind.</p>', 'Variante A: Direkte Antwort ohne sichtbaren Plan', 'Antworte auf Deutsch direkt auf die Frage. Gib nur eine kurze Empfehlung mit Aufstehzeit und Abfahrtszeit. Zeige keine getrennten Teilaufgaben, keine Tabelle und keine ausführliche Rechnung.', 'Variante B: Antwort mit sichtbarem Plan', 'Antworte auf Deutsch. Erstelle einen klaren, zeitlich geordneten und überprüfbaren Plan. Trenne Teilaufgaben und feste Zeiten. Rechne alle Abhängigkeiten nachvollziehbar rückwärts. Nenne die Aufstehzeit und den Zeitpunkt zum Verlassen des Hauses.', null, 20, 7);
INSERT INTO public."Element" (id, type, title, description, "taskA", "devPromptA", "taskB", "devPromptB", "devPromptC", position, "lessonId") VALUES (32, 'text', null, '<h2>Was Planung sichtbar macht</h2><p>Je komplexer der Schulweg wird, desto hilfreicher ist es, Teilaufgaben, feste Zeiten und Änderungen getrennt zu betrachten. Ein sichtbarer Plan lässt sich überprüfen und bei neuen Bedingungen gezielt anpassen.</p>', null, null, null, null, null, 30, 7);
INSERT INTO public."Element" (id, type, title, description, "taskA", "devPromptA", "taskB", "devPromptB", "devPromptC", position, "lessonId") VALUES (35, 'ai12', null, '<h2>Plan mit eigenem Feedback anpassen</h2><p>Erstelle in der Übung darüber eine KI-Antwort. Wähle mit einem der beiden Buttons die linke oder rechte Antwort als ursprünglichen Plan für Prompt 1 aus. Wähle für Prompt 2 eine Änderung aus der Tabelle oder beschreibe deine eigene gewünschte Änderung. Sende beide Prompts ab, um den Plan anpassen zu lassen. Übernimm anschließend die andere Antwort und vergleiche die Anpassungen mit derselben Änderung.</p><p><button type="button" onclick="copyPreviousAiSideOutput(this, 0)">Linke KI-Antwort übernehmen</button> <button type="button" onclick="copyPreviousAiSideOutput(this, 1)">Rechte KI-Antwort übernehmen</button></p><h3>Beispiele für Prompt 2: Änderung am Plan</h3><p>Übernimm zuerst einen Plan aus der jeweils angegebenen Version der Übung darüber in Prompt 1. Wähle dann eine Änderung aus der Tabelle oder schreibe eine eigene.</p><table><thead><tr><th>Beispiel</th><th>Änderung am Plan</th><th>In Prompt 2 einfügen</th></tr></thead><tbody><tr><td>1: Regen (Version 3: Mit Fahrrad)</td><td>Es regnet und ich kann nicht mit dem Fahrrad fahren. Stattdessen nehme ich den Bus: Zur Haltestelle gehe ich 5 Minuten. Der Bus fährt um 7:35 Uhr ab und braucht 15 Minuten zur Schule. Passe meinen Plan an. Wann muss ich jetzt aufstehen und das Haus verlassen, um spätestens um 8:00 Uhr in der Schule zu sein?</td><td><button type="button" onclick="fill2(this)">einfügen</button></td></tr><tr><td>2: Bus verpasst (Version 2: Mit Bus)</td><td>Ich habe den Bus um 7:35 Uhr verpasst. Der nächste Bus kommt 10 Minuten später an der Haltestelle an und braucht ebenfalls 15 Minuten zur Schule. Passe meinen Plan an. Um wie viel Uhr komme ich in der Schule an und bin ich noch rechtzeitig um 8:00 Uhr dort?</td><td><button type="button" onclick="fill2(this)">einfügen</button></td></tr><tr><td>3: Sonnenschein</td><td>Die Sonne scheint und ich möchte stattdessen zu Fuß zur Schule gehen. Zu Fuß dauert der Weg 30 Minuten. Passe meinen Plan an. Wann muss ich jetzt aufstehen und losgehen, damit ich weiterhin um 8:00 Uhr in der Schule bin?</td><td><button type="button" onclick="fill2(this)">einfügen</button></td></tr></tbody></table>', 'Prompt 1: Ursprünglicher Plan', 'Antworte auf Deutsch. Die erste Nachricht enthält den ursprünglichen Plan, die zweite Nachricht die gewünschte Änderung. Übernimm die unveränderten Teile des Plans, passe nur die von der Änderung betroffenen Schritte an und erkläre kurz die Folgen. Erstelle eine klare, überprüfbare Zeitleiste.', 'Prompt 2: Änderung am Plan', null, null, 45, 7);
INSERT INTO public."Element" (id, type, title, description, "taskA", "devPromptA", "taskB", "devPromptB", "devPromptC", position, "lessonId") VALUES (34, 'star', null, '<mark><h2><i class="fas fa-star"></i> Aufgabe: Was macht den Plan zuverlässig?</h2><p>Erkläre, warum ein Plan für den Schulweg bei festen Abfahrtszeiten und Änderungen nützlich ist. Beschreibe außerdem, welche Informationen bei Regen oder einem verpassten Bus angepasst werden müssen.</p><p>Löse diese Aufgabe, um einen Stern <i class="fas fa-star"></i> zu erhalten!</p></mark>', 'Deine Erklärung', 'Bewerte, ob die Antwort erklärt, dass ein Plan Teilaufgaben sichtbar macht. Sie soll außerdem nennen, dass bei Änderungen wie Regen oder einem verpassten Bus nur die betroffenen Schritte angepasst werden müssen. Wenn beide Ideen verständlich genannt werden, vergib einen Stern. Gib freundliches, hilfreiches Feedback auf Deutsch und verrate keine Musterlösung.', null, null, null, 50, 7);

